package actions

import (
	"github.com/Azure/spec-sla-bot/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Assignee)
// DB Table: Plural (assignees)
// Resource: Plural (Assignees)
// Path: Plural (/assignees)
// View Template Folder: Plural (/templates/assignees/)

// AssigneesResource is the resource for the Assignee model
type AssigneesResource struct {
	buffalo.Resource
}

// List gets all Assignees. This function is mapped to the path
// GET /assignees
func (v AssigneesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	assignees := &models.Assignees{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Assignees from the DB
	if err := q.All(assignees); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, assignees))
}

// Show gets the data for one Assignee. This function is mapped to
// the path GET /assignees/{assignee_id}
func (v AssigneesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Assignee
	assignee := &models.Assignee{}

	// To find the Assignee the parameter assignee_id is used.
	if err := tx.Find(assignee, c.Param("assignee_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, assignee))
}

// New renders the form for creating a new Assignee.
// This function is mapped to the path GET /assignees/new
func (v AssigneesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Assignee{}))
}

// Create adds a Assignee to the DB. This function is mapped to the
// path POST /assignees
func (v AssigneesResource) Create(c buffalo.Context) error {
	// Allocate an empty Assignee
	assignee := &models.Assignee{}

	// Bind assignee to the html form elements
	if err := c.Bind(assignee); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(assignee)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, assignee))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Assignee was created successfully")

	// and redirect to the assignees index page
	return c.Render(201, r.Auto(c, assignee))
}

// Edit renders a edit form for a Assignee. This function is
// mapped to the path GET /assignees/{assignee_id}/edit
func (v AssigneesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Assignee
	assignee := &models.Assignee{}

	if err := tx.Find(assignee, c.Param("assignee_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, assignee))
}

// Update changes a Assignee in the DB. This function is mapped to
// the path PUT /assignees/{assignee_id}
func (v AssigneesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Assignee
	assignee := &models.Assignee{}

	if err := tx.Find(assignee, c.Param("assignee_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Assignee to the html form elements
	if err := c.Bind(assignee); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(assignee)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, assignee))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Assignee was updated successfully")

	// and redirect to the assignees index page
	return c.Render(200, r.Auto(c, assignee))
}

// Destroy deletes a Assignee from the DB. This function is mapped
// to the path DELETE /assignees/{assignee_id}
func (v AssigneesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Assignee
	assignee := &models.Assignee{}

	// To find the Assignee the parameter assignee_id is used.
	if err := tx.Find(assignee, c.Param("assignee_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(assignee); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Assignee was destroyed successfully")

	// Redirect to the assignees index page
	return c.Render(200, r.Auto(c, assignee))
}
