package actions

import (
	"github.com/Azure/spec-sla-bot/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (EmailAssignee)
// DB Table: Plural (email_assignees)
// Resource: Plural (EmailAssignees)
// Path: Plural (/email_assignees)
// View Template Folder: Plural (/templates/email_assignees/)

// EmailAssigneesResource is the resource for the EmailAssignee model
type EmailAssigneesResource struct {
	buffalo.Resource
}

// List gets all EmailAssignees. This function is mapped to the path
// GET /email_assignees
func (v EmailAssigneesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	emailAssignees := &models.EmailAssignees{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all EmailAssignees from the DB
	if err := q.All(emailAssignees); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, emailAssignees))
}

// Show gets the data for one EmailAssignee. This function is mapped to
// the path GET /email_assignees/{email_assignee_id}
func (v EmailAssigneesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty EmailAssignee
	emailAssignee := &models.EmailAssignee{}

	// To find the EmailAssignee the parameter email_assignee_id is used.
	if err := tx.Find(emailAssignee, c.Param("email_assignee_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, emailAssignee))
}

// New renders the form for creating a new EmailAssignee.
// This function is mapped to the path GET /email_assignees/new
func (v EmailAssigneesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.EmailAssignee{}))
}

// Create adds a EmailAssignee to the DB. This function is mapped to the
// path POST /email_assignees
func (v EmailAssigneesResource) Create(c buffalo.Context) error {
	// Allocate an empty EmailAssignee
	emailAssignee := &models.EmailAssignee{}

	// Bind emailAssignee to the html form elements
	if err := c.Bind(emailAssignee); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(emailAssignee)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, emailAssignee))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "EmailAssignee was created successfully")

	// and redirect to the email_assignees index page
	return c.Render(201, r.Auto(c, emailAssignee))
}

// Edit renders a edit form for a EmailAssignee. This function is
// mapped to the path GET /email_assignees/{email_assignee_id}/edit
func (v EmailAssigneesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty EmailAssignee
	emailAssignee := &models.EmailAssignee{}

	if err := tx.Find(emailAssignee, c.Param("email_assignee_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, emailAssignee))
}

// Update changes a EmailAssignee in the DB. This function is mapped to
// the path PUT /email_assignees/{email_assignee_id}
func (v EmailAssigneesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty EmailAssignee
	emailAssignee := &models.EmailAssignee{}

	if err := tx.Find(emailAssignee, c.Param("email_assignee_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind EmailAssignee to the html form elements
	if err := c.Bind(emailAssignee); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(emailAssignee)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, emailAssignee))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "EmailAssignee was updated successfully")

	// and redirect to the email_assignees index page
	return c.Render(200, r.Auto(c, emailAssignee))
}

// Destroy deletes a EmailAssignee from the DB. This function is mapped
// to the path DELETE /email_assignees/{email_assignee_id}
func (v EmailAssigneesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty EmailAssignee
	emailAssignee := &models.EmailAssignee{}

	// To find the EmailAssignee the parameter email_assignee_id is used.
	if err := tx.Find(emailAssignee, c.Param("email_assignee_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(emailAssignee); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "EmailAssignee was destroyed successfully")

	// Redirect to the email_assignees index page
	return c.Render(200, r.Auto(c, emailAssignee))
}
