package actions

import (
	"github.com/Azure/spec-sla-bot/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (PRAssignee)
// DB Table: Plural (p_r_assignees)
// Resource: Plural (PRAssignees)
// Path: Plural (/p_r_assignees)
// View Template Folder: Plural (/templates/p_r_assignees/)

// PRAssigneesResource is the resource for the PRAssignee model
type PRAssigneesResource struct {
	buffalo.Resource
}

// List gets all PRAssignees. This function is mapped to the path
// GET /p_r_assignees
func (v PRAssigneesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	pRAssignees := &models.PRAssignees{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all PRAssignees from the DB
	if err := q.All(pRAssignees); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, pRAssignees))
}

// Show gets the data for one PRAssignee. This function is mapped to
// the path GET /p_r_assignees/{p_r_assignee_id}
func (v PRAssigneesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PRAssignee
	pRAssignee := &models.PRAssignee{}

	// To find the PRAssignee the parameter p_r_assignee_id is used.
	if err := tx.Find(pRAssignee, c.Param("p_r_assignee_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, pRAssignee))
}

// New renders the form for creating a new PRAssignee.
// This function is mapped to the path GET /p_r_assignees/new
func (v PRAssigneesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.PRAssignee{}))
}

// Create adds a PRAssignee to the DB. This function is mapped to the
// path POST /p_r_assignees
func (v PRAssigneesResource) Create(c buffalo.Context) error {
	// Allocate an empty PRAssignee
	pRAssignee := &models.PRAssignee{}

	// Bind pRAssignee to the html form elements
	if err := c.Bind(pRAssignee); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(pRAssignee)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, pRAssignee))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "PRAssignee was created successfully")

	// and redirect to the p_r_assignees index page
	return c.Render(201, r.Auto(c, pRAssignee))
}

// Edit renders a edit form for a PRAssignee. This function is
// mapped to the path GET /p_r_assignees/{p_r_assignee_id}/edit
func (v PRAssigneesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PRAssignee
	pRAssignee := &models.PRAssignee{}

	if err := tx.Find(pRAssignee, c.Param("p_r_assignee_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, pRAssignee))
}

// Update changes a PRAssignee in the DB. This function is mapped to
// the path PUT /p_r_assignees/{p_r_assignee_id}
func (v PRAssigneesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PRAssignee
	pRAssignee := &models.PRAssignee{}

	if err := tx.Find(pRAssignee, c.Param("p_r_assignee_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind PRAssignee to the html form elements
	if err := c.Bind(pRAssignee); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(pRAssignee)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, pRAssignee))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "PRAssignee was updated successfully")

	// and redirect to the p_r_assignees index page
	return c.Render(200, r.Auto(c, pRAssignee))
}

// Destroy deletes a PRAssignee from the DB. This function is mapped
// to the path DELETE /p_r_assignees/{p_r_assignee_id}
func (v PRAssigneesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PRAssignee
	pRAssignee := &models.PRAssignee{}

	// To find the PRAssignee the parameter p_r_assignee_id is used.
	if err := tx.Find(pRAssignee, c.Param("p_r_assignee_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(pRAssignee); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "PRAssignee was destroyed successfully")

	// Redirect to the p_r_assignees index page
	return c.Render(200, r.Auto(c, pRAssignee))
}
