package actions

import (
	"github.com/Azure/spec-sla-bot/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (PR)
// DB Table: Plural (p_rs)
// Resource: Plural (PRs)
// Path: Plural (/p_rs)
// View Template Folder: Plural (/templates/p_rs/)

// PRsResource is the resource for the PR model
type PRsResource struct {
	buffalo.Resource
}

// List gets all PRs. This function is mapped to the path
// GET /p_rs
func (v PRsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	pRs := &models.PRs{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all PRs from the DB
	if err := q.All(pRs); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, pRs))
}

// Show gets the data for one PR. This function is mapped to
// the path GET /p_rs/{p_r_id}
func (v PRsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PR
	pR := &models.PR{}

	// To find the PR the parameter p_r_id is used.
	if err := tx.Find(pR, c.Param("pr_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, pR))
}

// New renders the form for creating a new PR.
// This function is mapped to the path GET /p_rs/new
func (v PRsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.PR{}))
}

// Create adds a PR to the DB. This function is mapped to the
// path POST /p_rs
func (v PRsResource) Create(c buffalo.Context) error {
	// Allocate an empty PR
	pR := &models.PR{}

	// Bind pR to the html form elements
	if err := c.Bind(pR); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(pR)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, pR))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "PR was created successfully")

	// and redirect to the p_rs index page
	return c.Render(201, r.Auto(c, pR))
}

// Edit renders a edit form for a PR. This function is
// mapped to the path GET /p_rs/{p_r_id}/edit
func (v PRsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PR
	pR := &models.PR{}

	if err := tx.Find(pR, c.Param("pr_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, pR))
}

// Update changes a PR in the DB. This function is mapped to
// the path PUT /p_rs/{p_r_id}
func (v PRsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PR
	pR := &models.PR{}

	if err := tx.Find(pR, c.Param("pr_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind PR to the html form elements
	if err := c.Bind(pR); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(pR)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, pR))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "PR was updated successfully")

	// and redirect to the p_rs index page
	return c.Render(200, r.Auto(c, pR))
}

// Destroy deletes a PR from the DB. This function is mapped
// to the path DELETE /p_rs/{p_r_id}
func (v PRsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty PR
	pR := &models.PR{}

	// To find the PR the parameter p_r_id is used.
	if err := tx.Find(pR, c.Param("p_r_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(pR); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "PR was destroyed successfully")

	// Redirect to the p_rs index page
	return c.Render(200, r.Auto(c, pR))
}
