package actions

import (
	"github.com/Azure/spec-sla-bot/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Pullrequest)
// DB Table: Plural (pullrequests)
// Resource: Plural (Pullrequests)
// Path: Plural (/pullrequests)
// View Template Folder: Plural (/templates/pullrequests/)

// PullrequestsResource is the resource for the Pullrequest model
type PullrequestsResource struct {
	buffalo.Resource
}

// List gets all Pullrequests. This function is mapped to the path
// GET /pullrequests
func (v PullrequestsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	pullrequests := &models.Pullrequests{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Pullrequests from the DB
	if err := q.All(pullrequests); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, pullrequests))
}

// Show gets the data for one Pullrequest. This function is mapped to
// the path GET /pullrequests/{pullrequest_id}
func (v PullrequestsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Pullrequest
	pullrequest := &models.Pullrequest{}

	// To find the Pullrequest the parameter pullrequest_id is used.
	if err := tx.Find(pullrequest, c.Param("pullrequest_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, pullrequest))
}

// New renders the form for creating a new Pullrequest.
// This function is mapped to the path GET /pullrequests/new
func (v PullrequestsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Pullrequest{}))
}

// Create adds a Pullrequest to the DB. This function is mapped to the
// path POST /pullrequests
func (v PullrequestsResource) Create(c buffalo.Context) error {
	// Allocate an empty Pullrequest
	pullrequest := &models.Pullrequest{}

	// Bind pullrequest to the html form elements
	if err := c.Bind(pullrequest); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(pullrequest)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, pullrequest))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Pullrequest was created successfully")

	// and redirect to the pullrequests index page
	return c.Render(201, r.Auto(c, pullrequest))
}

// Edit renders a edit form for a Pullrequest. This function is
// mapped to the path GET /pullrequests/{pullrequest_id}/edit
func (v PullrequestsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Pullrequest
	pullrequest := &models.Pullrequest{}

	if err := tx.Find(pullrequest, c.Param("pullrequest_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, pullrequest))
}

// Update changes a Pullrequest in the DB. This function is mapped to
// the path PUT /pullrequests/{pullrequest_id}
func (v PullrequestsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Pullrequest
	pullrequest := &models.Pullrequest{}

	if err := tx.Find(pullrequest, c.Param("pullrequest_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Pullrequest to the html form elements
	if err := c.Bind(pullrequest); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(pullrequest)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, pullrequest))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Pullrequest was updated successfully")

	// and redirect to the pullrequests index page
	return c.Render(200, r.Auto(c, pullrequest))
}

// Destroy deletes a Pullrequest from the DB. This function is mapped
// to the path DELETE /pullrequests/{pullrequest_id}
func (v PullrequestsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Pullrequest
	pullrequest := &models.Pullrequest{}

	// To find the Pullrequest the parameter pullrequest_id is used.
	if err := tx.Find(pullrequest, c.Param("pullrequest_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(pullrequest); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Pullrequest was destroyed successfully")

	// Redirect to the pullrequests index page
	return c.Render(200, r.Auto(c, pullrequest))
}
